print("juice\\\\\\wrld")
print("I\'m \"exposed\"\nHell if I know")
print("I\'m the cause\vthe cause in a deep wound")
print("\bAint no bullshit ")
print("Made it this far\aif I can \tthen you can too")
print("\fI dont get it \f I dont get it")
print("All legends fall inthe makingSaw the\r truth")
print("\a\a\a\a\a\a\a\a\apolly cause there is")
print("%d" %45)
print("%o"%10000)
print("%E" %1540)
print("%r" %int)
print("%x" %999)
print("%f" %14.5)
print("%u"%-4456.56)
print( "%g%%"%10.33)
print("%c"%10013)